export const DANGEROUS_PATTERNS: { pattern: RegExp; label: string }[] = [
  { pattern: /\bos\.system\s*\(/, label: "os.system()" },
  { pattern: /\bsubprocess\b/, label: "subprocess" },
  { pattern: /\beval\s*\(/, label: "eval()" },
  { pattern: /\bexec\s*\(/, label: "exec()" },
  { pattern: /\b__import__\s*\(/, label: "__import__()" },
  { pattern: /\bshutil\.rmtree\s*\(/, label: "shutil.rmtree()" },
  { pattern: /\bopen\s*\(\s*['"]\/(?:etc|proc|sys|dev)/, label: "open() with sensitive path" },
];

interface SanitizeResult {
  flagged: boolean;
  sanitized: string;
  warnings: string[];
}

export function sanitizeCodeCell(code: string): SanitizeResult {
  const lines = code.split("\n");
  const warnings: string[] = [];
  let flagged = false;
  const outputLines: string[] = [];

  for (const line of lines) {
    let lineFlagged = false;
    for (const { pattern, label } of DANGEROUS_PATTERNS) {
      if (pattern.test(line)) {
        lineFlagged = true;
        flagged = true;
        warnings.push(`Potentially dangerous: ${label}`);
        break;
      }
    }
    if (lineFlagged) {
      outputLines.push("# WARNING: The following line was flagged as potentially dangerous. Review before executing.");
      outputLines.push(line);
    } else {
      outputLines.push(line);
    }
  }

  return {
    flagged,
    sanitized: outputLines.join("\n"),
    warnings,
  };
}

export const NOTEBOOK_WARNING_CELL = [
  "---\n",
  "\n",
  "> **This notebook was auto-generated by PaperToCode.**\n",
  "> Review all code cells before executing. Generated code may contain errors or unexpected behavior.\n",
  "\n",
  "---\n",
];
