import { test, expect } from "@playwright/test";
import path from "path";
import fs from "fs";

/**
 * Real E2E Quality Test — Uses a live Gemini API key and a real PDF.
 *
 * Requires environment variables:
 *   GEMINI_API_KEY  — A valid Gemini API key (AIza...)
 *   TEST_PDF_PATH   — Path to a real PDF file (optional, has default)
 *
 * Run: GEMINI_API_KEY=AIza... yarn test:quality
 * Skipped automatically in CI when GEMINI_API_KEY is not set.
 */

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const TEST_PDF_PATH =
  process.env.TEST_PDF_PATH ||
  "/Users/saurmehr/Downloads/GLIDE_Spotify.pdf";

const screenshotDir = path.join(__dirname, "..", "screenshots");

// Skip entire suite if no API key is provided
test.describe("Quality Test — Real Gemini E2E", () => {
  test.skip(!GEMINI_API_KEY, "GEMINI_API_KEY not set — skipping quality test");

  test(
    "full pipeline: upload real PDF → generate notebook → validate output",
    async ({ page }) => {
      // Ensure screenshot directory exists
      if (!fs.existsSync(screenshotDir)) {
        fs.mkdirSync(screenshotDir, { recursive: true });
      }

      // Verify the test PDF exists
      expect(fs.existsSync(TEST_PDF_PATH)).toBe(true);

      // Step 1: Navigate to app
      await page.goto("/");
      await page.screenshot({
        path: path.join(screenshotDir, "quality-01-home.png"),
        fullPage: true,
      });

      // Step 2: Enter API key
      const apiKeyInput = page.getByTestId("api-key-input");
      await apiKeyInput.fill(GEMINI_API_KEY!);
      await page.screenshot({
        path: path.join(screenshotDir, "quality-02-key-entered.png"),
        fullPage: true,
      });

      // Step 3: Select Pro model
      const proOption = page.getByTestId("model-option-pro");
      await expect(proOption).toBeVisible();
      await proOption.click();
      await page.screenshot({
        path: path.join(screenshotDir, "quality-03-model-selected.png"),
        fullPage: true,
      });

      // Step 4: Upload real PDF
      const fileInput = page.getByTestId("pdf-file-input");
      await fileInput.setInputFiles(TEST_PDF_PATH);

      // Step 5: Wait for PDF preview
      const preview = page.getByTestId("pdf-preview");
      await expect(preview).toBeVisible({ timeout: 5000 });
      await page.screenshot({
        path: path.join(screenshotDir, "quality-04-pdf-preview.png"),
        fullPage: true,
      });

      // Step 6: Click Generate
      const generateBtn = page.getByTestId("generate-button");
      await expect(generateBtn).toBeVisible();
      await generateBtn.click();

      // Step 7: Wait for progress display
      const progressDisplay = page.getByTestId("progress-display");
      await expect(progressDisplay).toBeVisible({ timeout: 5000 });
      await page.screenshot({
        path: path.join(screenshotDir, "quality-05-generating.png"),
        fullPage: true,
      });

      // Step 8: Wait for completion (up to 120s for Gemini to respond)
      const downloadSection = page.getByTestId("download-section");
      await expect(downloadSection).toBeVisible({ timeout: 120_000 });
      await page.screenshot({
        path: path.join(screenshotDir, "quality-06-complete.png"),
        fullPage: true,
      });

      // Step 9: Intercept the download
      const [download] = await Promise.all([
        page.waitForEvent("download"),
        page.getByTestId("download-button").click(),
      ]);

      const downloadPath = await download.path();
      expect(downloadPath).toBeTruthy();

      // Step 10: Read and validate the notebook
      const notebookContent = fs.readFileSync(downloadPath!, "utf-8");
      const notebook = JSON.parse(notebookContent);

      // Validation (a): Valid JSON with nbformat
      expect(notebook.nbformat).toBe(4);

      // Validation (b): Has paper_metadata with title
      const cells = notebook.cells as Array<{
        cell_type: string;
        source: string[];
      }>;
      const allText = cells.map((c) => c.source.join("")).join("\n");
      // The title should appear somewhere in the notebook
      expect(cells.length).toBeGreaterThan(0);

      // Validation (c): At least 5 cells
      expect(cells.length).toBeGreaterThanOrEqual(5);

      // Validation (d): Warning banner cell is present
      const warningCell = cells.find(
        (c) =>
          c.cell_type === "markdown" &&
          c.source.join("").includes("auto-generated by PaperToCode")
      );
      expect(warningCell).toBeDefined();

      // Validation (e): At least 1 code cell with Python-like content
      const codeCells = cells.filter((c) => c.cell_type === "code");
      expect(codeCells.length).toBeGreaterThanOrEqual(1);
      const hasImportOrDef = codeCells.some((c) => {
        const code = c.source.join("");
        return code.includes("import ") || code.includes("def ") || code.includes("class ");
      });
      expect(hasImportOrDef).toBe(true);

      await page.screenshot({
        path: path.join(screenshotDir, "quality-07-validated.png"),
        fullPage: true,
      });

      // Log summary
      console.log(`\n--- Quality Test Results ---`);
      console.log(`Cells: ${cells.length}`);
      console.log(`Code cells: ${codeCells.length}`);
      console.log(`Markdown cells: ${cells.length - codeCells.length}`);
      console.log(`Warning banner: present`);
      console.log(`Has Python code: ${hasImportOrDef}`);
      console.log(`Download file: ${download.suggestedFilename()}`);
      console.log(`----------------------------\n`);
    },
    { timeout: 150_000 }
  );
});
